### ISSUE TITLE
Pitch skeleton

### ISSUE THREAD

**Issue by aishwaryasharmaccoew** [aishwaryasharmaccoew/CIS6930-NLP#1]
Questions to answer

* What are you studying, and how will you study it?
* How has the problem been explored before?
* What are the expected results of your study What is the importance of this problem--how might the results be used? 
* What technologies/models/approaches will you use to study it?
* What metrics will you use in your study? What are your completion criteria--how will you know when you are done?

**Comment by singh-mansi** [comment]
Project pitch was delivered by me and we are waiting for the feedback

**Comment by aishwaryasharmaccoew** [comment]
**Presented pitch**

_**Team Name:**_    Linguistic Luminaries
_**Topic:**_    Using topic modeling to identify the correlation between lifestyle choices and mental health concerns from social media trends
_**Project Pitch:**_    We plan on examining how to use different topic modeling techniques such as LDA ,CTM and LSA to identify the correlation between lifestyle choices like “diet,” “exercise,” “and sleeping patterns,” etc., and mental health concerns such as “depression” and “anxiety” using Twitter posts.

The correlation between lifestyle choices and mental health concerns is an essential topic of research, as it has the potential to lead to intervention and prevention strategies for mental health awareness programs and health campaigns, as well as to provide NLP researchers an insight into how individuals discuss and perceive this relationship on social media.

There has been previous research on the relationship between mental health and the pandemic as well as on how to predict the severity of mental illness in online pro-eating disorder communities. Although there has not been any specific research linking mental health to general lifestyle choices, these studies would be a great place to start for us. Previous research hurdles include insufficient data and a lack of fine-grained analysis.

As both lifestyle choices and mental illnesses are broad fields, our solution would concentrate on determining precisely which lifestyle choice influences which mental disorder and determine if the mapping is many to one or many to many

We  aim to identify some common lifestyle choices and mental illnesses as retrieved from twitter data using topic modeling techniques and then compute the correlation coefficients for each subset/pair in the two data sets. Using NLP techniques, the research effort seeks to perform accurate topic modelling and then establish a correlation between the data. The LDA model uses the data scraped from Twitter using tools like tweepy to identify the subjects. The incapability of LDA to model topic correlation is one of its drawbacks. Here, we use the CTM model and logistic normal distribution to determine the association between the themes, and the outcome indicates the potency of the two NLP techniques for examining huge amounts of unstructured data.

We will be investigating the performance of the model in regard to several metrics such as topic coherence, classification accuracy, correlation, clustering evaluation, and scalability.
