### ISSUE TITLE
Initial experiment modelling

### ISSUE THREAD

**Issue by aishwaryasharmaccoew** [aishwaryasharmaccoew/CIS6930-NLP#10]
- Grooming the initial pitch
- Devising project architecture
- Possibly come up with a project roadmap

We can link any issues that contribute towards this here

**Comment by aishwaryasharmaccoew** [comment]
Based on my literature survey, these are the two topic modelling methods I found useful for experiment design and I have also mentioned how to use them for  performing correlation in our case. 
We need to decided on which one to use or perform a comparative study using both

https://docs.google.com/document/d/1ri9wrVLL5FbbJsoxTxGdUJjHP2oMSB11jwUDcTUZGXA/edit?usp=sharing

**Comment by aishwaryasharmaccoew** [comment]
@singh-mansi can you look into using BERt as our 3rd model and also is STM/CTM okay as our second model? 
LSA is almost done

**Comment by singh-mansi** [comment]
We have decided not to move forward with BERT because of its complex workings and how it does not align well with our project scope. So we have decided to use word embeddings technique as our third model.
