### ISSUE TITLE
Project proposal Presentation

### ISSUE THREAD

**Issue by singh-mansi** [aishwaryasharmaccoew/CIS6930-NLP#3]

**Comment by aishwaryasharmaccoew** [comment]
@singh-mansi can you please provide a description for this issue ?
Is it for further grooming of the presented pitch ?

**Comment by singh-mansi** [comment]
It's for the project proposal presentation that I am assuming we will have to present in the coming weeks. I just want to start thinking in that direction so we have all the components for the proposal

**Comment by aishwaryasharmaccoew** [comment]
@sruthi99999 please add the proposal presentation here and close oput the issue

**Comment by singh-mansi** [comment]
The presentation was successful. Priya and Aishwarya presented via zoom 
Presentation link : https://docs.google.com/presentation/d/1fhOxJHqfhHtrlj8VZ-NvNq4hN8DwCWjfALz1sE6j_sQ/edit#slide=id.p

Feedback: The hypothesis needs to be more NLP focused (which is why we thought of pivoting this project towards a comparative study)
