### ISSUE TITLE
healthcare_twitter_analysis

### ISSUE THREAD

**Issue by aishwaryasharmaccoew** [aishwaryasharmaccoew/CIS6930-NLP#6]
- Includes getting the data to a usable form for experiment modelling.
- And putting a sample up in the Data folder of this repo

**Comment by nitinrameshuf** [comment]
Dataset incompatible and Unavaliable, repalcing with TMDT dataset.
Highly promising includes 2 subsets: 
1) Tweets from people who have disclosed having mental health issues.
2) Tweets from people who have never spoken of mental health.

**Comment by aishwaryasharmaccoew** [comment]
As Discussed, Disregarding twitter data due to redily available sub-reddits
